=== NolwennCG/Dasson-ur-galon/XML/MM2_DUG_Poeme.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT TEI (#PCDATA | teiHeader | body)*>
    <!ELEMENT teiHeader (#PCDATA | fileDesc)*>
        <!ELEMENT fileDesc (#PCDATA | titleStmt | editionStmt | publicationStmt | sourceDesc | profileDesc)*>
            <!ELEMENT titleStmt (#PCDATA | title | author)*>
                <!ELEMENT title (#PCDATA)>
                <!ATTLIST title type CDATA #IMPLIED>
                <!ELEMENT author (#PCDATA)>
                <!ATTLIST author key CDATA #IMPLIED>
                <!ATTLIST author ref CDATA #IMPLIED>
            <!ELEMENT editionStmt (#PCDATA | edition | respStmt)*>
                <!ELEMENT edition (#PCDATA)>
                <!ELEMENT respStmt (#PCDATA | name | resp)*>
                    <!ELEMENT name (#PCDATA)>
                    <!ATTLIST name xml:id CDATA #IMPLIED>
                    <!ELEMENT resp (#PCDATA)>
            <!ELEMENT publicationStmt (#PCDATA | publisher | date | availability)*>
                <!ELEMENT availability (#PCDATA | licence | p)*>
                <!ATTLIST availability status CDATA #IMPLIED>
                    <!ELEMENT licence (#PCDATA)>
                    <!ATTLIST licence target CDATA #IMPLIED>
            <!ELEMENT sourceDesc (#PCDATA | bibl)*>
                <!ELEMENT bibl (#PCDATA | author | title | editor | pubPlace | publisher | date | biblScope | ref)*>
                    <!ELEMENT editor (#PCDATA)>
                    <!ELEMENT publisher (#PCDATA)>
                    <!ELEMENT pubPlace (#PCDATA)>
                    <!ELEMENT biblScope (#PCDATA)>
                    <!ELEMENT ref (#PCDATA)>
                    <!ATTLIST ref target CDATA #IMPLIED>
            <!ELEMENT profileDesc (#PCDATA | creation | langUsage)*>
                <!ELEMENT creation (#PCDATA | date)*>
                    <!ELEMENT date (#PCDATA)>
                    <!ATTLIST date when CDATA #IMPLIED>
                <!ELEMENT langUsage (#PCDATA | language)*>
                    <!ELEMENT language (#PCDATA)>
                    <!ATTLIST language ident CDATA #IMPLIED>

    <!ELEMENT body (#PCDATA | div)*>
        <!ELEMENT div (#PCDATA | cit | dateline | head | lg | label | p | pb)*>
        <!ATTLIST div type CDATA #IMPLIED>
            <!ELEMENT cit (#PCDATA | abbr | pc | seg | pb | quote | bibl)*>
                <!ELEMENT quote (#PCDATA | abbr | pc | seg | pb)*>
            <!ELEMENT dateline (#PCDATA | origDate | origPlace)*>
                <!ELEMENT origPlace (#PCDATA | abbr | pc | seg | note | choice)*>
                <!ELEMENT origDate (#PCDATA | abbr | pc | seg | note | choice)*>
            <!ELEMENT head (#PCDATA | abbr | pc | seg | note | choice)*>
            <!ATTLIST head type CDATA #IMPLIED>
            <!ELEMENT lg (#PCDATA | l | pb)*>
                <!ELEMENT l (#PCDATA | abbr | pc | seg | pb | note | choice)*>
                    <!ELEMENT pc (#PCDATA | choice)*>
                    <!ATTLIST pc type CDATA #IMPLIED>
                    <!ELEMENT abbr (#PCDATA | choice)*>
                    <!ATTLIST abbr type CDATA #IMPLIED>
                    <!ELEMENT seg (#PCDATA | choice)*>
                    <!ATTLIST seg type CDATA #IMPLIED>
                        <!ELEMENT choice (#PCDATA | orig | reg | corr | sic)*>
                        <!ELEMENT orig (#PCDATA)>
                        <!ELEMENT reg (#PCDATA)>
                        <!ELEMENT sic (#PCDATA)>
                        <!ELEMENT corr (#PCDATA)>
                        <!ATTLIST corr resp CDATA #IMPLIED>
                    <!ELEMENT note (#PCDATA | choice | hi)*>
                    <!ATTLIST note resp CDATA #IMPLIED>
                    <!ATTLIST note n CDATA #IMPLIED>
                        <!ELEMENT hi (#PCDATA)>
                        <!ATTLIST hi rend CDATA #IMPLIED>
            <!ELEMENT label (#PCDATA | abbr | pc | seg | pb)*>
            <!ELEMENT p (#PCDATA | abbr | pc | seg | pb)*>
            <!ELEMENT pb (#PCDATA)>
            <!ATTLIST pb n CDATA #IMPLIED>

=== NolwennCG/Dasson-ur-galon/XML/MM2_DUG_13.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TEI
  SYSTEM "MM2_DUG_Poeme.dtd">
<TEI><teiHeader><fileDesc><titleStmt><title type="main">Dasson ur galon</title><title type="sub">Perag plégein ho penn ?</title><author key="Herrieu, Loeiz (1879-1953)" ref="https://data.bnf.fr/fr/12041305/loeiz_herrieu/">Loeiz Herrieu</author></titleStmt><editionStmt><edition>Université de Lille</edition><respStmt><name xml:id="NC">Nolwenn Chevalier</name><resp>éditrice critique</resp></respStmt></editionStmt><publicationStmt><publisher>Université de Lille</publisher><date when="2019"/><availability status="restricted"><licence target="http://creativecommons.org/licenses/by-nc-nd/3.0/fr/"/><p>Copyright © 2014 Université de Lille.</p><p>Cette ressource électronique protégée par le code de la propriété intellectuelle sur les bases de données (L341-1) est mise à disposition de la communauté scientifique internationale par l’Université de Lille, selon les termes de la licence Creative Commons : « Attribution - Pas d’Utilisation Commerciale - Pas de Modification 3.0 France (CC BY-NC-ND 3.0 FR) ».</p><p>Attribution : afin de référencer la source, toute utilisation ou publication dérivée de cette ressource électroniques comportera le nom de l’Université de Lille et surtout l’adresse Internet de la ressource.</p><p>Pas d’Utilisation Commerciale : dans l’intérêt de la communauté scientifique, toute utilisation commerciale est interdite.</p><p>Pas de Modification : l’Université de Lille s’engage à améliorer et à corriger cette ressource électronique, notamment en intégrant toutes les contributions extérieures. La diffusion de versions modifiées de cette ressource n’est pas souhaitable.</p></availability></publicationStmt><sourceDesc><bibl><author>Loeiz Herrieu</author>, « Perag plegiñ ho penn ? », <title>Dasson ur Galon</title>, <pubPlace>Brest</pubPlace>, <publisher>Brud Nevez</publisher>, <date>1983</date>, <biblScope>141 p.</biblScope>. PDF : <ref target="http://bibliotheque.idbe-bzh.org/data/cle_113/Dasson_ur_Galon_.pdf">Idbe-bzh</ref>. </bibl></sourceDesc><profileDesc><creation><date when="1983"/></creation><langUsage><language ident="bre"/></langUsage></profileDesc></fileDesc></teiHeader><body><div type="poem">
<pb n="50"/>
<head>Perag pl<seg type="signes_diacritiques"><choice><orig>é</orig><reg>e</reg></choice></seg>g<seg type="monophtongaison"><choice><orig>ei</orig><reg>i</reg></choice></seg><seg type="nasalisation"><choice><orig>n</orig><reg>ñ</reg></choice></seg> ho penn ?</head>       
<lg>
<l>O pla<seg type="trigramme_diacritique"><choice><orig>h</orig><reg>c’h</reg></choice></seg> ! pera<seg type="voisement"><choice><orig>g</orig><reg>k</reg></choice></seg> pl<seg type="signes_diacritiques"><choice><orig>é</orig><reg>e</reg></choice></seg>g<seg type="monophtongaison"><choice><orig>ei</orig><reg>i</reg></choice></seg><seg type="nasalisation"><choice><orig>n</orig><reg>ñ</reg></choice></seg> ho penn</l>
<l><seg type="signes_diacritiques"><choice><orig>É</orig><reg>E</reg></choice></seg>dan bourd<seg type="diphtongaison"><choice><orig>eu</orig><reg>où</reg></choice></seg> amoed <seg type="amenuisement_voyelle"><choice><orig>e</orig><reg>a</reg></choice></seg>r bed ?</l>
<l><pc type="elision"><choice><reg>‘</reg></choice></pc>Ar <seg type="amenuisement_voyelle"><choice><orig>e</orig><reg>a</reg></choice></seg>n douar-m<seg type="nasalisation"><choice><orig>an</orig><reg>añ</reg></choice></seg>, krou<seg type="amenuisement_voyelle"><choice><orig>è</orig><reg>a</reg></choice></seg>dur erbe<seg type="voisement"><choice><orig>d</orig><reg>t</reg></choice></seg></l>
<l>N<pc type="elision"><choice><reg>’</reg></choice></pc>en d<seg type="en_cours"><choice><orig>é</orig><reg>eus</reg></choice></seg> ken kaer <seg type="signes_diacritiques"><choice><orig>é</orig><reg>e</reg></choice></seg>n <seg type="signes_diacritiques"><choice><orig>é</orig><reg>e</reg></choice></seg> anien<seg type="amuissement_consonne"><choice><orig>n</orig></choice></seg>.</l>     
</lg>       
<lg>
<l>Seul gw<seg type="signes_diacritiques"><choice><orig>é</orig><reg>e</reg></choice></seg><seg type="trigramme_diacritique"><choice><orig>h</orig><reg>ch</reg></choice></seg> m'en d<seg type="digramme"><choice><orig>e</orig><reg>eu</reg></choice></seg>s klasket mab-d<seg type="signes_diacritiques"><choice><orig>é</orig><reg>e</reg></choice></seg>n</l>
<l>Ob<seg type="signes_diacritiques"><choice><orig>é</orig><reg>e</reg></choice></seg>r un dou<seg type="signes_diacritiques"><choice><orig>é</orig><reg>e</reg></choice></seg> ag <seg type="amenuisement_voyelle"><choice><orig>e</orig><reg>a</reg></choice></seg>r G<seg type="signes_diacritiques"><choice><orig>é</orig><reg>e</reg></choice></seg>ned.</l>
<l>Ge<seg type="voisement"><choice><orig>d</orig><reg>t</reg></choice></seg> ho <seg type="trigramme_diacritique"><choice><orig>h</orig><reg>c’h</reg></choice></seg>or<seg type="mutation_consonantique"><choice><orig>v</orig><reg>f</reg></choice></seg> en d<seg type="digramme"><choice><orig>e</orig><reg>eu</reg></choice></seg>s <seg type="nasalisation"><choice><orig>ean</orig><reg>eñ</reg></choice></seg> gwisket, </l>
<l>Ho kor<seg type="mutation_consonantique"><choice><orig>v</orig><reg>f</reg></choice></seg>, pennob<seg type="signes_diacritiques"><choice><orig>é</orig><reg>e</reg></choice></seg>r <seg type="amenuisement_voyelle"><choice><orig>e</orig><reg>a</reg></choice></seg>n Eden.</l>     
</lg>       
<lg>
<l>A p<seg type="amenuisement_voyelle"><choice><orig>e</orig><reg>a</reg></choice></seg> venn <seg type="amenuisement_voyelle"><choice><orig>e</orig><reg>a</reg></choice></seg>r <seg type="trigramme_diacritique"><choice><orig>H</orig><reg>C’h</reg></choice></seg>rou<seg type="signes_diacritiques"><choice><orig>é</orig><reg>e</reg></choice></seg>our, un d<seg type="signes_diacritiques"><choice><orig>é</orig><reg>e</reg></choice></seg><seg type="amuissement_voyelle"><choice><reg>i</reg></choice></seg><seg type="amuissement_consonne"><choice><reg>z</reg></choice></seg>, </l>
<l>Diav<seg type="signes_diacritiques"><choice><orig>ê</orig><reg>ae</reg></choice></seg>z<seg type="monophtongaison"><choice><orig>ei</orig><reg>i</reg></choice></seg><seg type="nasalisation"><choice><orig>n</orig><reg>ñ</reg></choice></seg> <seg type="signes_diacritiques"><choice><orig>É</orig><reg>E</reg></choice></seg> vra<seg type="lettre_ramiste"><choice><orig>ù</orig><reg>v</reg></choice></seg>it<seg type="signes_diacritiques"><choice><orig>é</orig><reg>e</reg></choice></seg><seg type="amuissement_consonne"><choice><reg>z</reg></choice></seg>, </l>
<l>N'ho kr<seg type="en_cours"><choice><orig>o</orig><reg>ou</reg></choice></seg>a ket a fang, <pc type="elision"><choice><reg>‘</reg></choice></pc><seg type="signes_diacritiques"><choice><orig>è</orig><reg>e</reg></choice></seg>l Adam ;</l>     
</lg>       
<lg>
<l>Goud<seg type="signes_diacritiques"><choice><orig>é</orig><reg>e</reg></choice></seg> d'<seg type="signes_diacritiques"><choice><orig>É</orig><reg>E</reg></choice></seg> zaou<seg type="amenuisement_voyelle"><choice><orig>o</orig><reg>a</reg></choice></seg>rn bou<seg type="voisement"><choice><orig>d</orig><reg>t</reg></choice></seg> gol<seg type="trigramme_diacritique"><choice><orig>h</orig><reg>c’h</reg></choice></seg>et,</l>
<l><seg type="amuissement_consonne"><choice><reg>H</reg></choice></seg><seg type="en_cours"><choice><orig>O</orig><reg>o</reg></choice></seg>ll-vra<seg type="lettre_ramiste"><choice><orig>ù</orig><reg>v</reg></choice></seg> <seg type="nasalisation"><choice><orig>Ean</orig><reg>Eñ</reg></choice></seg> ho tr<seg type="signes_diacritiques"><choice><orig>è</orig><reg>e</reg></choice></seg>s, 'n ur l<seg type="signes_diacritiques"><choice><orig>a</orig><reg>â</reg></choice></seg>re<seg type="voisement"><choice><orig>d</orig><reg>t</reg></choice></seg> :</l>
<l>« Ane<seg type="digramme"><choice><orig>h</orig><reg>zh</reg></choice></seg>i 'vo <seg type="signes_diacritiques"><choice><orig>é</orig><reg>e</reg></choice></seg> <seg type="amuissement_consonne"><choice><orig>h</orig></choice></seg>r<seg type="en_cours"><choice><orig>ee</orig><reg>ai</reg></choice></seg>m<seg type="amuissement_consonne"><choice><reg>p</reg></choice></seg> Or Mamm. »</l>     
</lg>
</div></body></TEI>
